### ISSUE TITLE
Reinforcements Improvement

### ISSUE THREAD

**Issue by sargken** [astruyk/Ares#195] opened 2015-05-11 16:24 UTC
Make Reinforcements use Mods also like RHS.

**Comment by TheOtherTaylor** [comment] 2015-05-12 00:54
I think #124 might be what you're looking for.

**Comment by sargken** [comment] 2015-05-13 23:05
Yes that is it

**Comment by astruyk** [comment] 2015-07-02 19:35
Closing as dupe of #124

**Closed by astruyk** 2015-07-02 19:35 UTC
